# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OrganizedGUI.ui',
# licensing of 'OrganizedGUI.ui' applies.
#
# Created: Wed Nov 27 09:37:59 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from  PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_clientB = QtWidgets.QPushButton(self.centralwidget)
        self.add_clientB.setGeometry(QtCore.QRect(70, 30, 101, 41))
        self.add_clientB.setObjectName("add_clientB")
        self.add_productB = QtWidgets.QPushButton(self.centralwidget)
        self.add_productB.setGeometry(QtCore.QRect(70, 90, 101, 41))
        self.add_productB.setObjectName("add_productB")
        self.add_techB = QtWidgets.QPushButton(self.centralwidget)
        self.add_techB.setGeometry(QtCore.QRect(70, 160, 101, 41))
        self.add_techB.setObjectName("add_techB")
        self.renovation = QtWidgets.QPushButton(self.centralwidget)
        self.renovation.setGeometry(QtCore.QRect(70, 220, 101, 41))
        self.renovation.setObjectName("renovation")
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(400, 20, 471, 431))
        self.groupBox1.setObjectName("groupBox1")
        self.label_2 = QtWidgets.QLabel(self.groupBox1)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox1)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 61, 31))
        self.label_3.setObjectName("label_3")
        self.client_name = QtWidgets.QLineEdit(self.groupBox1)
        self.client_name.setGeometry(QtCore.QRect(70, 50, 113, 20))
        self.client_name.setObjectName("client_name")
        self.client_location = QtWidgets.QLineEdit(self.groupBox1)
        self.client_location.setGeometry(QtCore.QRect(70, 120, 113, 20))
        self.client_location.setObjectName("client_location")
        self.push_client = QtWidgets.QPushButton(self.groupBox1)
        self.push_client.setGeometry(QtCore.QRect(90, 170, 75, 23))
        self.push_client.setObjectName("push_client")
        self.mesge_labelName = QtWidgets.QLabel(self.groupBox1)
        self.mesge_labelName.setGeometry(QtCore.QRect(80, 80, 47, 13))
        self.mesge_labelName.setText("")
        self.mesge_labelName.setObjectName("mesge_labelName")
        self.templetlabellocation = QtWidgets.QLabel(self.groupBox1)
        self.templetlabellocation.setGeometry(QtCore.QRect(90, 150, 47, 13))
        self.templetlabellocation.setText("")
        self.templetlabellocation.setObjectName("templetlabellocation")
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(60, 270, 241, 231))
        self.groupBox2.setObjectName("groupBox2")
        self.label_5 = QtWidgets.QLabel(self.groupBox2)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 61, 31))
        self.label_5.setObjectName("label_5")
        self.product_name = QtWidgets.QLineEdit(self.groupBox2)
        self.product_name.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.product_name.setObjectName("product_name")
        self.push_product = QtWidgets.QPushButton(self.groupBox2)
        self.push_product.setGeometry(QtCore.QRect(130, 180, 75, 23))
        self.push_product.setObjectName("push_product")
        self.label_7 = QtWidgets.QLabel(self.groupBox2)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 61, 31))
        self.label_7.setObjectName("label_7")
        self.id_pclient = QtWidgets.QLineEdit(self.groupBox2)
        self.id_pclient.setGeometry(QtCore.QRect(80, 110, 113, 20))
        self.id_pclient.setObjectName("id_pclient")
        self.mesge_labeClient = QtWidgets.QLabel(self.groupBox2)
        self.mesge_labeClient.setGeometry(QtCore.QRect(10, 190, 47, 13))
        self.mesge_labeClient.setText("")
        self.mesge_labeClient.setObjectName("mesge_labeClient")
        self.label_nameproduct = QtWidgets.QLabel(self.groupBox2)
        self.label_nameproduct.setGeometry(QtCore.QRect(60, 80, 47, 13))
        self.label_nameproduct.setObjectName("label_nameproduct")
        self.labe_idclient = QtWidgets.QLabel(self.groupBox2)
        self.labe_idclient.setGeometry(QtCore.QRect(40, 150, 47, 13))
        self.labe_idclient.setObjectName("labe_idclient")
        self.groupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox3.setGeometry(QtCore.QRect(190, 40, 201, 161))
        self.groupBox3.setObjectName("groupBox3")
        self.label_9 = QtWidgets.QLabel(self.groupBox3)
        self.label_9.setGeometry(QtCore.QRect(20, 30, 61, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox3)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 61, 31))
        self.label_10.setObjectName("label_10")
        self.tech_name = QtWidgets.QLineEdit(self.groupBox3)
        self.tech_name.setGeometry(QtCore.QRect(80, 40, 113, 20))
        self.tech_name.setObjectName("tech_name")
        self.tech_username = QtWidgets.QLineEdit(self.groupBox3)
        self.tech_username.setGeometry(QtCore.QRect(80, 100, 113, 20))
        self.tech_username.setObjectName("tech_username")
        self.push_tech = QtWidgets.QPushButton(self.groupBox3)
        self.push_tech.setGeometry(QtCore.QRect(100, 230, 75, 23))
        self.push_tech.setObjectName("push_tech")
        self.label_11 = QtWidgets.QLabel(self.groupBox3)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 61, 31))
        self.label_11.setObjectName("label_11")
        self.tech_pass = QtWidgets.QLineEdit(self.groupBox3)
        self.tech_pass.setGeometry(QtCore.QRect(80, 160, 113, 20))
        self.tech_pass.setObjectName("tech_pass")
        self.msagelabel_username = QtWidgets.QLabel(self.groupBox3)
        self.msagelabel_username.setGeometry(QtCore.QRect(110, 130, 47, 13))
        self.msagelabel_username.setObjectName("msagelabel_username")
        self.label_passmesage = QtWidgets.QLabel(self.groupBox3)
        self.label_passmesage.setGeometry(QtCore.QRect(100, 190, 47, 13))
        self.label_passmesage.setObjectName("label_passmesage")
        self.labelnameof_masgetech = QtWidgets.QLabel(self.groupBox3)
        self.labelnameof_masgetech.setGeometry(QtCore.QRect(100, 70, 47, 13))
        self.labelnameof_masgetech.setObjectName("labelnameof_masgetech")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1144, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.add_clientB.setText(QtWidgets.QApplication.translate("MainWindow", "Add Client", None, -1))
        self.add_productB.setText(QtWidgets.QApplication.translate("MainWindow", "Add Product", None, -1))
        self.add_techB.setText(QtWidgets.QApplication.translate("MainWindow", "Add Technician", None, -1))
        self.renovation.setText(QtWidgets.QApplication.translate("MainWindow", "Renovation", None, -1))
        self.groupBox1.setTitle(QtWidgets.QApplication.translate("MainWindow", "Add Client", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Name :", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Location :", None, -1))
        self.push_client.setText(QtWidgets.QApplication.translate("MainWindow", "Push", None, -1))
        self.groupBox2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Add Product", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Name :", None, -1))
        self.push_product.setText(QtWidgets.QApplication.translate("MainWindow", "Push", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "ID Client :", None, -1))
        self.label_nameproduct.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.labe_idclient.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.groupBox3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Add Technician", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Name :", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "username :", None, -1))
        self.push_tech.setText(QtWidgets.QApplication.translate("MainWindow", "Push", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "passworde :", None, -1))
        self.msagelabel_username.setText(QtWidgets.QApplication.translate("MainWindow", "yy", None, -1))
        self.label_passmesage.setText(QtWidgets.QApplication.translate("MainWindow", "yy", None, -1))
        self.labelnameof_masgetech.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))

